### ISSUE TITLE
3D Pack 0917 update with torch==2.4.0 (need to fix errors). Backup your python_embeded before the update!

### ISSUE THREAD

**Issue by jakechai** [MrForExample/ComfyUI-3D-Pack#306]
**Errors occur after the update and ComfyUI fails to import the 3D Pack. Rolling back to the previous stable version of ComfyUI python_embeded to solve. But I don't know if it will affect the new features.**

pytorch version: 2.4.0+cu121
E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : cudaMallocAsync
Using xformers cross attention

E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Traceback (most recent call last):
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\comfy_extras\nodes_audio.py", line 1, in <module>
    import torchaudio
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torchaudio\__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torchaudio\_extension\__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torchaudio\_extension\utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch\_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 376, in __init__
OSError: [WinError 127] 找不到指定的程序。

Cannot import E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\comfy_extras\nodes_audio.py module for custom nodes: [WinError 127] 找不到指定的程序。
Traceback (most recent call last):
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 50, in <module>
    from FlexiCubes.flexicubes_trainer import FlexiCubesTrainer
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\FlexiCubes\flexicubes_trainer.py", line 13, in <module>
    from .loss import sdf_reg_loss
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\FlexiCubes\loss.py", line 9, in <module>
    import torch_scatter
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch_scatter\__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch\_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 376, in __init__
OSError: [WinError 127] 找不到指定的程序。

**Comment by Blahblahdenver** [comment]
i thought I had messed it up somehow so i reinstalled comfyui with the torch it says to on the front page and now its forcing specific versions of everything. are we not using torch-2.3.0+cu121-cp311-cp311-win_amd64.whl torchvision-0.18.0+cu121-cp311-cp311-win_amd64.whl torchaudio-2.3.0+cu121-cp311-cp311-win_amd64.whl anymore? what do we do here?

**Comment by RegRurutu** [comment]
same here, installing 3D pack come with torch==2.4.0 - making a failed install - or I am missing something ?

**Comment by Elpien** [comment]
same here

**Comment by Blahblahdenver** [comment]
i think ive got it working, dont know why but build_config.yaml specifies versions of things, change the version of torch to 2.3.0, torchvision to 0.18.0, and xformers to 0.0.26 post1

**Comment by Elpien** [comment]
> i think ive got it working, dont know why but build_config.yaml specifies versions of things, change the version of torch to 2.3.0, torchvision to 0.18.0, and xformers to 0.0.26 post1

well actually not sure if that fixed it, but i followed your suggestion, got another error, that my c++  redis couldn't be found and after fixing that it seems to work... 
Thank you :)

**Comment by Blahblahdenver** [comment]
> > i think ive got it working, dont know why but build_config.yaml specifies versions of things, change the version of torch to 2.3.0, torchvision to 0.18.0, and xformers to 0.0.26 post1
> 
> well actually not sure if that fixed it, but i followed your suggestion, got another error, that my c++ redis couldn't be found and after fixing that it seems to work... Thank you :)

how did you fix that? I'm running in a conda env and I'm getting the error from slang that its finding a version of cl.exe somewhere it doesn't exist and saying its a different version than what I actually have on my pc.

**Comment by jakechai** [comment]
> i think ive got it working, dont know why but build_config.yaml specifies versions of things, change the version of torch to 2.3.0, torchvision to 0.18.0, and xformers to 0.0.26 post1

It works for me! thanks!

**Comment by MrForExample** [comment]
I'll rebuild all the wheels to support torch 2.4.0 and torchvision 0.19 before end of this week 👍

**Comment by MrForExample** [comment]
Hi, I just rebuilt all the wheels for `Windows, python 3.10, 3.11, 3.12, cuda 11.8. 12.1, pytorch 2.4.0`, please let me know if there are any other problems 👍

**Comment by jakechai** [comment]
> Hi, I just rebuilt all the wheels for `Windows, python 3.10, 3.11, 3.12, cuda 11.8. 12.1, pytorch 2.4.0`, please let me know if there are any other problems 👍

Thanks for the wheels! But the errors are the same as before, so I have to roll it back.
Can the new features be run on torch==2.3.0, torchvision==0.18, xformers==0.0.26.post1?

**Comment by Firetheft** [comment]
Installation is annoying enough, and then...

**Comment by MrForExample** [comment]
Yeah, I just realized a problem yesterday, if you have installed the package for torch 2.3.0 before then you have to uninstall those pre-built wheels before you can install the new packages, otherwise pip install will skip it, I'll update the install.py to auto uninstall the old packages

**Comment by MrForExample** [comment]
Ok, I just updated the install.py to make it run `pip install --no-deps --force-reinstall <pre-built wheels>`, it should be able to overwrite those old wheels in your ComfyUI python environment now

**Comment by Firetheft** [comment]
I spent half a day deploying the torch2.3.0 environment. When I thought it was about to succeed, 3d-pack helped me update the environment to 2.4.0. Obviously, this was a disaster!

**Comment by MrForExample** [comment]
@Firetheft 
Yeah, sorry for the trouble, a few days ago when I changed the config file, I didn't realise simply update from torch 2.3.0 to 2.4.0 would need rebuilt all the dependencies.
But it should work now by pulling the main, pip -r requirement.txt and running install.py
let me know here if there are other things I can help 👍

**Comment by Firetheft** [comment]
> @Firetheft Yeah, sorry for the trouble, a few days ago when I changed the config file, I didn't realise simply update from torch 2.3.0 to 2.4.0 would need rebuilt all the dependencies. But it should work now by pulling the main, pip -r requirement.txt and running install.py let me know here if there are other things I can help 👍

I just reverted my environment to 2.3.0, and then I stupidly installed 3d-pack again in Manager...

**Comment by jakechai** [comment]
> Ok, I just updated the install.py to make it run `pip install --no-deps --force-reinstall <pre-built wheels>`, it should be able to overwrite those old wheels in your ComfyUI python environment now

I tried, errors are still there.
I have fixed the torchaudio one by upgrading it to 'torchaudio-2.4.0+cu121-cp311-cp311-win_amd64.whl' by myself. 
But the torch_scatter error remains, I can't find a proper version of it.

**Comment by felixsoong0825** [comment]
> > Ok, I just updated the install.py to make it run `pip install --no-deps --force-reinstall <pre-built wheels>`, it should be able to overwrite those old wheels in your ComfyUI python environment now
> 
> I tried, errors are still there. But it works after the fixes blow: torchaudio: `pip install torchaudio-2.4.0+cu121-cp311-cp311-win_amd64.whl` by myself. torch_scatter: `pip install --force-reinstall torch-scatter==2.1.2 -f https://data.pyg.org/whl/torch-2.4.0+cu121.html` to upgrade to `torch-scatter-2.1.2+pt24cu121`
> 
> **warnings** E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch. @torch.library.impl_abstract("xformers_flash::flash_fwd") E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch. @torch.library.impl_abstract("xformers_flash::flash_bwd")
> 
> E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead. @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32) E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\kiui\nn__init__.py:31: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead. @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32) E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\kiui\nn__init__.py:37: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead. @torch.cuda.amp.custom_bwd E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\ops.py:38: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead. @custom_fwd(cast_inputs=torch.float32) E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\ops.py:44: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead. @custom_bwd Warn!: E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\craftsman\utils\checkpoint.py:39: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead. @torch.cuda.amp.custom_fwd Warn!: E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\craftsman\utils\checkpoint.py:50: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead. @torch.cuda.amp.custom_bwd

I did almost the same, but I still have a 304 cuda error, I can successfully install but not able to open it. After future warning I have a 304 error

**Comment by jakechai** [comment]
Check the NVIDIA settings and the display driver.

**Comment by JimWang151** [comment]
> I spent half a day deploying the torch2.3.0 environment. When I thought it was about to succeed, 3d-pack helped me update the environment to 2.4.0. Obviously, this was a disaster!

Same as me.Force install torch 2.4.0,.

> @Firetheft Yeah, sorry for the trouble, a few days ago when I changed the config file, I didn't realise simply update from torch 2.3.0 to 2.4.0 would need rebuilt all the dependencies. But it should work now by pulling the main, pip -r requirement.txt and running install.py let me know here if there are other things I can help 👍

still force install torch 2.4.0.

**Comment by jakechai** [comment]
> still force install torch 2.4.0.

It works for torch 2.4.0: https://github.com/MrForExample/ComfyUI-3D-Pack/issues/306#issuecomment-2365380973

**Comment by v4r4rth** [comment]
![image](https://github.com/user-attachments/assets/df464b0e-c607-4e66-ab5f-6a59f4fe6800)

How to get the torchausio wheel?

**Comment by v4r4rth** [comment]
My torchaudio error is gone, but the torch-scatter is still bugged out...

```
(comfyui) sid@ai-ubuntu-01-v02:/DaTa1/sid/ComfyUI$ pip install --force-reinstall torch-scatter==2.1.2 -f https://data.pyg.org/whl/torch-2.4.0+cu121.html
Looking in links: https://data.pyg.org/whl/torch-2.4.0+cu121.html
Collecting torch-scatter==2.1.2
  Downloading https://data.pyg.org/whl/torch-2.4.0%2Bcu121/torch_scatter-2.1.2%2Bpt24cu121-cp311-cp311-linux_x86_64.whl (10.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 5.8 MB/s eta 0:00:00
Installing collected packages: torch-scatter
  Attempting uninstall: torch-scatter
    Found existing installation: torch_scatter 2.1.2
    Uninstalling torch_scatter-2.1.2:
      Successfully uninstalled torch_scatter-2.1.2
Successfully installed torch-scatter-2.1.2+pt24cu121
(comfyui) sid@ai-ubuntu-01-v02:/DaTa1/sid/ComfyUI$ ./start.sh
[MaraScott] Initialization
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-08 11:40:14.828814
** Platform: Linux
** Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
** Python executable: /home/sid/miniconda3/envs/comfyui/bin/python
** ComfyUI Path: /DaTa1/sid/ComfyUI
** Log path: /DaTa1/sid/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Stable-Video-Diffusion
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_MaraScott_Nodes
   1.2 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 48887 MB, total RAM 92522 MB
pytorch version: 2.4.0+cu121
/home/sid/miniconda3/envs/comfyui/lib/python3.11/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/home/sid/miniconda3/envs/comfyui/lib/python3.11/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
xformers version: 0.0.27.post2
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA A40-48Q : native
Using xformers cross attention
[Prompt Server] web root: /DaTa1/sid/ComfyUI/web
/home/sid/miniconda3/envs/comfyui/lib/python3.11/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
------------------------------------------
### N-Suite Revision: ae7cc848 
Current version of packaging: 23.2
Version of cpuinfo: Not found
Current version of git: 3.1.43
Current version of moviepy: 1.0.3
Current version of cv2: 4.10.0
Current version of skbuild: 0.17.6
Version of typing: Not found
Current version of diskcache: 5.6.3
Current version of llama_cpp: 0.2.26+cu121
Current version of timm: 1.0.9
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
!!!Hallo path was added to /home/sid/miniconda3/envs/comfyui/lib/python3.11/site-packages/Hallo.pth
 if meet No module named 'hallo' error,please restart comfyui
Hallo use cache models,make sure your 'pretrained_models' complete
/DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Hallo/pretrained_models
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[Moondream] trying to update model versions...ok
[Moondream] found model versions: 2024-03-04, 2024-03-06, 2024-03-13, 2024-04-02, 2024-05-08, 2024-05-20, 2024-07-23, 2024-08-26
[Moondream] model revsion references:
latest -> 92d3d73b6fd61ab84d9fe093a9c7fd8c04bf2c0d
2023-03-04 -> b3d72d14957e9965facc14f53dc01c7e3bbe0eec
2024-03-04 -> b3d72d14957e9965facc14f53dc01c7e3bbe0eec
2024-03-05 -> 4a8fa31450e8def597abae38a8fa915d18e90b9f
2024-03-06 -> c064b4c517bbdbbad6351b1959c90b79858822be
2024-03-13 -> 2b705eea63f9bff6dae9b52c2daeb26bc10e4aeb
2024-04-02 -> 9ba2958f5a886de83fa18a235d651295a05b4d13
2024-05-08 -> 6275e4316f99adc1f8fd7f63301327f1ac4bfe5e
2024-05-20 -> af5f98991c2661d0c4448ff6c2fb3c19e74f1c02
2024-07-23 -> 79671eae7b5340017e91065d09c1ce1a352c0e8d
2024-08-26 -> 92d3d73b6fd61ab84d9fe093a9c7fd8c04bf2c0d

[MaraScott] Loaded
----------Jake Upgrade Nodes Loaded----------

[rgthree-comfy] Loaded 42 magnificent nodes. 🎉

python_executable_path:  /home/sid/miniconda3/envs/comfyui/bin/python
python_embeded_path:  /home/sid/miniconda3/envs/comfyui/bin
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /DaTa1/sid/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
/DaTa1/sid/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

FizzleDorf Custom Nodes: Loaded
/DaTa1/sid/ComfyUI
############################################
/DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-NAI-styler/CSV
############################################
[]
############################################
Error:
[Errno 17] File exists: '/DaTa1/sid/ComfyUI/custom_nodes/ComfyLiterals/js' -> '/DaTa1/sid/ComfyUI/web/extensions/ComfyLiterals'
Failed to create symlink to /DaTa1/sid/ComfyUI/web/extensions/ComfyLiterals. Please copy the folder manually.
Source: /DaTa1/sid/ComfyUI/custom_nodes/ComfyLiterals/js
Target: /DaTa1/sid/ComfyUI/web/extensions/ComfyLiterals
[ComfyUI-Easy-Use] server: v1.2.4 Loaded
[ComfyUI-Easy-Use] web root: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Easy-Use/web_version/v2 Loaded
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Torch version: 2.4.0+cu121
Total VRAM 48887 MB, total RAM 92522 MB
pytorch version: 2.4.0+cu121
xformers version: 0.0.27.post2
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA A40-48Q : native
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/DaTa1/sid/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "The only limit to our realization of tomorrow will be our doubts of today." - Franklin D. Roosevelt

[Crystools INFO] Crystools version: 1.19.0
[Crystools INFO] CPU: Intel Xeon Processor (Icelake) - Arch: Arch unknown - OS: Linux 6.8.0-45-generic
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA A40-48Q
[Crystools INFO] NVIDIA Driver: 535.183.01
[Crystools ERROR] Could not get GPU temperature. Turning off this feature. Not Supported
[comfy_mtb] | INFO -> loaded 86 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8845/mtb if you want more information.
[tinyterraNodes] Loaded
sageattn not found, using sdpa
sageattn not found, using sdpa
sageattn not found, using sdpa
### Loading: ComfyUI-Inspire-Pack (V1.3)
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
### Loading: ComfyUI-Manager (V2.51.5)
### ComfyUI Revision: 2746 [614377ab] | Released on '2024-10-07'
Traceback (most recent call last):
  File "/DaTa1/sid/ComfyUI/nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-3D-Pack/__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sid/miniconda3/envs/comfyui/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 50, in <module>
    from FlexiCubes.flexicubes_trainer import FlexiCubesTrainer
  File "/DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-3D-Pack/MVs_Algorithms/FlexiCubes/flexicubes_trainer.py", line 13, in <module>
    from .loss import sdf_reg_loss
  File "/DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-3D-Pack/MVs_Algorithms/FlexiCubes/loss.py", line 9, in <module>
    import torch_scatter
  File "/home/sid/miniconda3/envs/comfyui/lib/python3.11/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/sid/miniconda3/envs/comfyui/lib/python3.11/site-packages/torch/_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "/home/sid/miniconda3/envs/comfyui/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/sid/miniconda3/envs/comfyui/lib/python3.11/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

Cannot import /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-3D-Pack module for custom nodes: /home/sid/miniconda3/envs/comfyui/lib/python3.11/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
### [START] ComfyUI AlekPet Nodes v1.0.29.1 ###
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading] 
Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading] 
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading] 
Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading] 
Node -> PoseNode: PoseNode [Loading] 
Node -> IDENode: IDENode [Loading] 
Node -> PainterNode: PainterNode [Loading] 
### [END] ComfyUI AlekPet Nodes ###
--------------
*ComfyUI_Jags_VectorMagic- nodes_loaded*
--------------
### Loading: ComfyUI-Impact-Pack (V7.9)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[Impact Pack] Wildcards loading done.
[Allor]: 0 nodes were overridden.
[Allor]: 12 modules were enabled.
[Allor]: 98 nodes were loaded.

Import times for custom nodes:
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Dream-Interpreter
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Image-Selector
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-PixelResolutionCalculator
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/sd-dynamic-thresholding
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Florence-2
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/Comfyui_TTP_Toolset
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-RAVE
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/lora-info
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfy-image-saver
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_Noise
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-HQ-Image-Save
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyLiterals
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Universal-Styler
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Image-Saver
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/masquerade-nodes-comfyui
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUi-Ollama-YN
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfyui-lama-remover
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-MakeFrame
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_densediffusion
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_JPS-Nodes
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfyui-inpaint-nodes
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/Comfy_KepListStuff
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-IC-Light
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-AutomaticCFG
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfyui-various
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/wlsh_nodes
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfyui-dream-video-batches
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Unique3D
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfyui-dream-project
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Florence2
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-KJNodes
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Allor
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_Jags_VectorMagic
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-JakeUpgrade
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-MimicMotionWrapper
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/facerestore_cf
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Stable-Video-Diffusion
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Crystools
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfyui-reactor-node
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.0 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.1 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfyui_segment_anything
   0.1 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.1 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfyui-ollama
   0.1 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.1 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_omost
   0.1 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Fluxpromptenhancer
   0.2 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_MaraScott_Nodes
   0.3 seconds: /DaTa1/sid/ComfyUI/custom_nodes/comfy_mtb
   0.3 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-AdvancedLivePortrait
   0.4 seconds (IMPORT FAILED): /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-3D-Pack
   0.4 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_CatVTON_Wrapper
   0.4 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_FaceAnalysis
   0.5 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Hallo
   0.5 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-Hangover-Moondream
   0.8 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-SUPIR
   1.2 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet
   1.3 seconds: /DaTa1/sid/ComfyUI/custom_nodes/ComfyUI-N-Nodes
   1.5 seconds: /DaTa1/sid/ComfyUI/custom_nodes/was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8845
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json

```

**Comment by jakechai** [comment]
> torch_scatter: `pip install --force-reinstall torch-scatter==2.1.2 -f https://data.pyg.org/whl/torch-2.4.0+cu121.html` to upgrade to `torch-scatter-2.1.2+pt24cu121`

Did you try this? @v4r4rth

**Comment by v4r4rth** [comment]
@jakechai yes, 

> > torch_scatter: `pip install --force-reinstall torch-scatter==2.1.2 -f https://data.pyg.org/whl/torch-2.4.0+cu121.html` to upgrade to `torch-scatter-2.1.2+pt24cu121`
> 
> Did you try this? @v4r4rth

**Comment by jakechai** [comment]
@v4r4rth I'm not sure whether it is the same issue:
https://github.com/pyg-team/pytorch_geometric/issues/999

**Comment by MrForExample** [comment]
Hi all, I just updated the [pre-builds](https://github.com/MrForExample/Comfy3D_Pre_Builds) for 
`Windows; Python 3.10, 3.11, 3.12; pytorch 2.5.0, torchvision 0.20.0, xformer 0.28.0 post2`
Hope you had a good weekend :)
