### ISSUE TITLE
WONDER3D error

### ISSUE THREAD

**Issue by kakachiex2** [MrForExample/ComfyUI-3D-Pack#79]
I get this error when I get to this point Large Multiview Gaussian Model node.

Error occurred when executing [Comfy3D] Large Multiview Gaussian Model:

User specified an unsupported autocast device_type 'cuda'

File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 1420, in run_LGM
with torch.autocast(device_type=device, dtype=WEIGHT_DTYPE):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\amp\autocast_mode.py", line 241, in __init__
raise RuntimeError(

**Comment by kakachiex2** [comment]
It's the first time using this node setup is the example node to test this feature, the others TripoAR work nice I will test all the workflow to see how they work and I post everything here.

**Comment by oliverban** [comment]
Hey! First of, thanks for this pack!

I am getting the same error but with the MVDream pipeline, all goes well until:

[Comfy3D] [Load_Large_Multiview_Gaussian_Model] loaded model ckpt from C:\Users\Oliver\Documents\Github\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\checkpoints/lgm\model_fp16.safetensors
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\Oliver\Documents\Github\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oliver\Documents\Github\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oliver\Documents\Github\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oliver\Documents\Github\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oliver\Documents\Github\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 1420, in run_LGM
    with torch.autocast(device_type=device, dtype=WEIGHT_DTYPE):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oliver\Documents\Github\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\amp\autocast_mode.py", line 241, in __init__
    raise RuntimeError(
RuntimeError: User specified an unsupported autocast device_type 'cuda'


Any idea what is happening?

**Comment by MrForExample** [comment]
That's wired, I'll take a look soon 👍

**Comment by MrForExample** [comment]
Sorry for the trouble guys, this is a bug from my carelessness, I didn't check the type of device parameter before I changed it:

![Screenshot 2024-03-07 105406](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/62230687/3e2f3581-e682-46d9-b8e3-83b9d96e2dc7)

I changed it back, it's fixed now, let me know if there is any other problem 👍

**Comment by kakachiex2** [comment]
Confirmed Wondr3d working no bugs.
![Screenshot 2024-03-07 151429](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/1762112/7b2b8ea3-1777-40de-bb54-113effbaac43)

**Comment by zhanghongyong123456** [comment]
> Sorry for the trouble guys, this is a bug from my carelessness, I didn't check the type of device parameter before I changed it:
> 
> ![Screenshot 2024-03-07 105406](https://private-user-images.githubusercontent.com/62230687/310833011-3e2f3581-e682-46d9-b8e3-83b9d96e2dc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjQwODUsIm5iZiI6MTcwOTg2Mzc4NSwicGF0aCI6Ii82MjIzMDY4Ny8zMTA4MzMwMTEtM2UyZjM1ODEtZTY4Mi00NmQ5LWI4ZTMtODNiOWQ5NmUyZGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAyMDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNzc3ZTk0ZTQ5Y2Y0YWRlMTEwOWU0OGQ2YjRhNTUxZGFlZThmN2Y3ODVjYzkwMDM4MjQ0OGQzMDVhZmJlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FGMSu4_xZhj69SHJoSAzPnV-XX5rkR0I55oc0wN6UFQ)
> 
> I changed it back, it's fixed now, let me know if there is any other problem 👍

when   i   test  ,i   have  other  error,i  reinstall pytorch,and   Ninja,  my  pytorch  2.1.2 cuda 12.1   Cuda: 12.1, Ninja 1.11.1.1,The problem still exists,I installed the source code(diff-gaussian-rasterization,nvdiffrast,pytorch_scatter,pytorch3d,torchmcubes)

![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/48466610/fa57d510-242b-4d17-b759-f952cd4e051c)

**Comment by zhanghongyong123456** [comment]
> > Sorry for the trouble guys, this is a bug from my carelessness, I didn't check the type of device parameter before I changed it:
> > ![Screenshot 2024-03-07 105406](https://private-user-images.githubusercontent.com/62230687/310833011-3e2f3581-e682-46d9-b8e3-83b9d96e2dc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjQwODUsIm5iZiI6MTcwOTg2Mzc4NSwicGF0aCI6Ii82MjIzMDY4Ny8zMTA4MzMwMTEtM2UyZjM1ODEtZTY4Mi00NmQ5LWI4ZTMtODNiOWQ5NmUyZGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAyMDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNzc3ZTk0ZTQ5Y2Y0YWRlMTEwOWU0OGQ2YjRhNTUxZGFlZThmN2Y3ODVjYzkwMDM4MjQ0OGQzMDVhZmJlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FGMSu4_xZhj69SHJoSAzPnV-XX5rkR0I55oc0wN6UFQ)
> > I changed it back, it's fixed now, let me know if there is any other problem 👍
> 
> when i test ,i have other error,i reinstall pytorch,and Ninja, my pytorch 2.1.2 cuda 12.1 Cuda: 12.1, Ninja 1.11.1.1,The problem still exists,I installed the source code(diff-gaussian-rasterization,nvdiffrast,pytorch_scatter,pytorch3d,torchmcubes)
> 
> ![image](https://private-user-images.githubusercontent.com/48466610/311094301-fa57d510-242b-4d17-b759-f952cd4e051c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjU0OTUsIm5iZiI6MTcwOTg2NTE5NSwicGF0aCI6Ii80ODQ2NjYxMC8zMTEwOTQzMDEtZmE1N2Q1MTAtMjQyYi00ZDE3LWI3NTktZjk1MmNkNGUwNTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAyMzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTBkMTUwZGU4ZTNjYjE3Mjc2MDc2ZTc5YjU2ZmY3YjMxNDgxYjllMDBmNGQ5MjMwMDJlZmFiMDY2MTM3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J1EDGkMu0RoDM2WMaiRMzelM_wrcfla8qMY7f-m0oms)
I added environment variables based on this answer. The Ninja path was not found in windows
https://github.com/MrForExample/ComfyUI-3D-Pack/issues/35#issuecomment-1956343485

**Comment by oliverban** [comment]
> > Sorry for the trouble guys, this is a bug from my carelessness, I didn't check the type of device parameter before I changed it:
> > ![Screenshot 2024-03-07 105406](https://private-user-images.githubusercontent.com/62230687/310833011-3e2f3581-e682-46d9-b8e3-83b9d96e2dc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjQwODUsIm5iZiI6MTcwOTg2Mzc4NSwicGF0aCI6Ii82MjIzMDY4Ny8zMTA4MzMwMTEtM2UyZjM1ODEtZTY4Mi00NmQ5LWI4ZTMtODNiOWQ5NmUyZGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAyMDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNzc3ZTk0ZTQ5Y2Y0YWRlMTEwOWU0OGQ2YjRhNTUxZGFlZThmN2Y3ODVjYzkwMDM4MjQ0OGQzMDVhZmJlYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FGMSu4_xZhj69SHJoSAzPnV-XX5rkR0I55oc0wN6UFQ)
> > I changed it back, it's fixed now, let me know if there is any other problem 👍
> 
> when i test ,i have other error,i reinstall pytorch,and Ninja, my pytorch 2.1.2 cuda 12.1 Cuda: 12.1, Ninja 1.11.1.1,The problem still exists,I installed the source code(diff-gaussian-rasterization,nvdiffrast,pytorch_scatter,pytorch3d,torchmcubes)
> 
> ![image](https://private-user-images.githubusercontent.com/48466610/311094301-fa57d510-242b-4d17-b759-f952cd4e051c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MDQxMTUsIm5iZiI6MTcwOTkwMzgxNSwicGF0aCI6Ii80ODQ2NjYxMC8zMTEwOTQzMDEtZmE1N2Q1MTAtMjQyYi00ZDE3LWI3NTktZjk1MmNkNGUwNTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDEzMTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTM2NWYxOWYwNDI2YjA3YTc3NmVlN2Y2YTQwZDIyNWI5OGU3ODAwMjY3ZDk3NzM5ZjVmNjgxNjUwMWE0YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NZ4Lrie-GtnEvEJ7i5SYC640vP7-ChU6TC_tJF54gO8)

Yep, I am also getting the Ninja error.
